articles/urls.py
from django.urls import path

from .views import (about, article_create, article_delete, article_detail,
                    article_update, article_list)

app_name = 'articles'
urlpatterns = [
    path('', article_list, name='list'),
    path('articles/<int:pk>', article_detail, name='detail'),
    path('articles/create', article_create, name='create'),
    path('articles/<int:pk>/delete', article_delete, name='delete'),
    path('articles/<int:pk>/update', article_update, name='update'),
    path('about/', about, name='about'),
]

blogbro/urls.py
import users.views as users_views
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import include, path

urlpatterns = [
    path('register/', users_views.RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(
        template_name='users/login.html',
        redirect_authenticated_user=True), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('admin/', admin.site.urls),
    path('', include('articles.urls')),
]

articles/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse_lazy

User = get_user_model()


class Article(models.Model):
    title = models.CharField(
        max_length=100, blank=False, null=False)
    excerpt = models.CharField(max_length=200, blank=False, null=False)
    content = models.TextField(blank=False, null=False)
    created_at = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='articles', default=None)

    def get_absolute_url(self):
        return reverse_lazy("articles:detail", kwargs={"pk": self.pk})

    def __str__(self):
        return self.title

users/models.py
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    pass

users/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

User = get_user_model()


class CustomUserCreationForm(UserCreationForm):
    class Meta():
        model = User
        fields = ('username', 'password1', 'password2')

articles/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.urls import reverse_lazy
from django.views.generic import TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView

from .models import Article


class ArticleListView(ListView):
    model = Article
    context_object_name = 'articles'
    ordering = ['-created_at']


class ArticleDetailView(DetailView):
    model = Article

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = self.object.title
        return context


class ArticleCreateView(LoginRequiredMixin, CreateView):
    model = Article
    fields = ['title', 'excerpt', 'content']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('articles:detail', kwargs={'pk': self.object.id})


class ArticleUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Article
    fields = ['title', 'excerpt', 'content']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = f'Update {self.object.title}'
        return context

    def test_func(self):
        article = self.get_object()
        return self.request.user == article.author

    def get_success_url(self):
        return reverse_lazy('articles:detail', kwargs={'pk': self.object.id})


class ArticleDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Article
    success_url = reverse_lazy('articles:list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = f'Delete {self.object.title}'
        return context

    def test_func(self):
        article = self.get_object()
        return self.request.user == article.author


class AboutView(TemplateView):
    template_name = 'articles/about.html'

users/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView

from .forms import CustomUserCreationForm


class RegisterView(CreateView):
    template_name = 'users/register.html'
    success_url = reverse_lazy('login')
    form_class = CustomUserCreationForm

articles/templates/articles/about.html
{% extends 'articles/base.html' %}

{% block title %}About{% endblock title %}

{% block content %}
  <h1>About BlogBro</h1>
  <p>
    Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quos quia, corporis
    distinctio voluptate ex excepturi laudantium ab inventore blanditiis neque
    atque unde voluptatibus repellendus odit maiores deserunt velit quidem
    adipisci voluptas eligendi! Velit quod nemo, sapiente optio architecto
    provident fugiat? Id aliquam sequi magnam nostrum voluptas ipsa rem ipsam ex
    commodi inventore vero, nihil cupiditate consectetur deserunt praesentium enim
    perferendis dignissimos veniam dolore fugiat architecto quia nobis, vitae
    incidunt. Aperiam perferendis dolorum, hic, ad praesentium illum, illo iure
    modi aliquid libero eaque! Architecto cumque omnis mollitia molestias non sit,
    laboriosam inventore esse ullam, nam atque magni distinctio quae blanditiis
    quisquam dignissimos. Hic sit vero porro! Est quisquam beatae amet enim quo
    voluptatem cumque? Corrupti, eius sapiente cupiditate sequi culpa facilis
    molestias minima delectus molestiae exercitationem aut voluptatibus, ipsam
    nisi repellat dolor vitae omnis ipsum sit praesentium. Facere alias molestiae
    quibusdam doloribus laudantium voluptatibus, architecto fugit cumque aut
    voluptatem voluptate dolorem corrupti ullam omnis, inventore libero a
    accusantium adipisci optio. A iure vero atque? Ad, animi odio aperiam corrupti
    vitae iste placeat sit non officia voluptatibus ut quos tempora tempore ab
    nihil, blanditiis veniam quibusdam, velit consequatur delectus. Possimus sequi
    veritatis, quis ab hic eligendi sed ducimus. Quod est vel asperiores.
  </p>
{% endblock content %}

articles/templates/articles/article_confirm_delete.html
{% extends 'articles/base.html' %}

{% block title %} Delete {{article.title}}? {% endblock title %}

{% block content %}
  <h1 class="mb-3">{{ article.title }}</h1>
  <h6 class="text-muted mb-3">Are you sure you want to delete this article?</h6>
  <form action="{% url 'articles:delete' article.id %}" method="POST">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Yes, Delete</button>
    <a
      href="{% url 'articles:detail' article.id %}"
      class="btn btn-secondary"
      class="ms-3"
      >Cancel</a
    >
  </form>

{% block title %}
  Delete {{article.title}}
{% endblock title %}

{% block content %}
  <h1 class="mb-3">{{ article.title }}</h1>
  <h6 class="text-muted mb-3">Are you sure you want to delete this article?</h6>
  <form action="{% url 'articles:delete' article.id %}" method="POST">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger">Yes, Delete</button>
    <a
      href="{% url 'articles:detail' article.id %}"
      class="btn btn-secondary"
      class="ms-3"
      >Cancel</a
    >
  </form>
{% endblock content %}

articles/templates/articles/article_detail.html
{% extends 'articles/base.html' %}

{% block title %}{{ article.title }}{% endblock title %}

{% block content %}
  <article class="col-10 mx-auto p-5 shadow-lg mb-5">
    <h1 class="mb-2 text-center">{{ article.title }}</h1>
    <h6 class="text-muted mb-3 text-center">{{ article.excerpt }}</h6>

    <div class="text-black d-flex justify-content-center align-items-center">
      <h6>Published {{article.created_at | timesince}} ago</h6>
      <h6 class="mx-3">.</h6>
      <h6>Article by {{article.author.username}}</h6>
    </div>

    <p class="lead col-10 mx-auto">{{ article.content }}</p>

    {% if user and user == article.author %}
    <div class="d-flex justify-content-center align-items-center">
      <a href="{% url 'articles:update' article.id %}" class="btn btn-info btn-lg"
        >Edit</a
      >

      <a
        href="{% url 'articles:delete' article.id %}"
        class="btn btn-danger btn-lg ms-3"
        >Delete</a
      >
    </div>
    {% endif %}
  </article>
{% endblock content %}

articles/templates/articles/article_form.html
{% extends 'articles/base.html' %}

{% load crispy_forms_tags %}

{% block title %}
  {% if article %}
    Update {{ article.title }}
  {% else %}
    Create New Article
  {% endif %}
{% endblock title %}

{% block content%}
  <form
    action="
      {% if article %}
        {% url 'articles:update' article.id %}
      {% else %}
        {% url 'articles:create' %}
      {% endif %}
    "
    method="POST"
    class="mx-auto col-6"
  >
    {% csrf_token %}
    <fieldset class="form-group mb-5 shadow-lg p-5">
      <legend class="border-bottom pb-2 mb-4 text-center">
        <h2>
          {% if article %}
            Update {{ article.title }}
          {% else %}
            Create new Article
          {% endif %}
        </h2>
      </legend>
      <div class="mb-3">{{ form.title | as_crispy_field }}</div>

      <div class="mb-3">{{ form.excerpt | as_crispy_field }}</div>

      <div class="mb-3">{{ form.content | as_crispy_field }}</div>

      <div class="d-flex justify-content-center align-items-center">
        <button type="submit" class="btn btn-success">
          {% if article %}
            Update
          {% else %}
            Submit
          {% endif %}
        </button>

  <form
    action="
      {% if article %}
        {% url 'articles:update' article.id %}
      {% else %}
        {% url 'articles:create' %}
      {% endif %}"
    method="POST"
    class="mx-auto col-8"
  >
    {% csrf_token %}
    <fieldset class="form-group mb-5 shadow-lg p-5">
      <legend class="border-bottom pb-2 mb-4 text-center">
        <h2>
          {% if article %}
            Update {{ article.title }}
          {% else %}
            Create New Article
          {% endif %}
        </h2>
      </legend>
      <div class="mb-3">{{ form.title | as_crispy_field }}</div>

      <div class="mb-3">{{ form.excerpt | as_crispy_field }}</div>

      <div class="mb-3">{{ form.content | as_crispy_field }}</div>

      <div class="d-flex justify-content-center align-items-center">
        <button type="submit" class="btn btn-success">
          {% if article %}
            Update
          {% else %}
            Submit
          {% endif %}
        </button>

        <a
          href="
            {% if article %}
              {% url 'articles:detail' article.id %}
            {% else %}
              {% url 'articles:list' %}
            {% endif %}"
          class="btn btn-outline-secondary ms-3"
          >Cancel</a
        >
      </div>
    </fieldset>
  </form>
{% endblock content %}

articles/templates/articles/article_list.html
{% extends 'articles/base.html' %}

{% block content %}

  <h1 class="mb-3">All Articles</h1>
  {% for article in articles %}
  <div class="col-md-6">
    {% include 'articles/partials/_article.html' with article=article %}
  </div>
  {% endfor %}

{% endblock content %}

articles/templates/articles/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      href="{% static 'articles/bootstrap.min.css' %}"
      rel="stylesheet"
      crossorigin="anonymous"
    />
    <title>
      {% if title %} BlogBro - {{ title }} {% else %} BlogBro {% endif %}
    </title>
  </head>
  <body>
    {% include 'articles/partials/_header.html' %}
    <main class="container">
      {% if messages %}
        {% for message in messages %}
          <div
            class="alert alert-warning alert-{{message.tags}} fade show"
            role="alert"
          >
            <span>{{message}}</span>
            <button
              type="button"
              class="btn-close float-end text-end"
              data-bs-dismiss="alert"
              aria-label="Close"
            />
          </div>
        {% endfor %}
      {% endif %}

      <section>
        {% block content %}{% endblock content %}
      </section>
    </main>
  </body>
</html>

articles/templates/articles/confirm_delete.html
{% extends 'articles/base.html' %} {% block content %}
<h1 class="mb-3">{{ article.title }}</h1>
<h6 class="text-muted mb-3">Are you sure you want to delete this article?</h6>
<form action="{% url 'articles:delete' article.id %}" method="POST">
  {% csrf_token %}
  <button type="submit" class="btn btn-danger">Yes, Delete</button>
  <a
    href="{% url 'articles:details' article.id %}"
    class="btn btn-secondary"
    class="ms-3"
    >Cancel</a
  >
</form>

{% endblock content %}

articles/templates/articles/details.html
{% extends 'articles/base.html' %} {% block content %}

<h1 class="mb-3">{{ article.title }}</h1>

<h6 class="text-muted mb-3">{{ article.excerpt }}</h6>

<p class="lead">{{ article.content }}</p>

<a href="{% url 'articles:update' article.id %}" class="btn btn-info btn-lg"
  >Edit</a
>

<a
  href="{% url 'articles:delete' article.id %}"
  class="btn btn-danger btn-lg ms-3"
  >Delete</a
>

{% endblock content %}

articles/templates/articles/form.html
{% extends 'articles/base.html' %} {% load crispy_forms_tags %}

<!---->

{% block content%}

<form
  action="{% if article %}{% url 'articles:update' article.id %}{% else %}{% url 'articles:create' %}{% endif %}"
  method="POST"
  class="mx-auto col-6"
>
  {% csrf_token %}
  <fieldset class="form-group mb-5 shadow-lg p-5">
    <legend class="border-bottom pb-2 mb-4 text-center">
      <h2>
        {% if article %}Update {{ article.title }} {% else %}Create new
        Article{% endif %}
      </h2>
    </legend>
    <div class="mb-3">{{ form.title | as_crispy_field }}</div>

    <div class="mb-3">{{ form.excerpt | as_crispy_field }}</div>

    <div class="mb-3">{{ form.content | as_crispy_field }}</div>

    <button type="submit" class="btn btn-success">
      {% if article %}Update{% else %}Submit{% endif %}
    </button>

    <a href="{% url 'articles:index' %}" class="btn btn-outline-secondary ms-3"
      >Cancel</a
    >
  </fieldset>
</form>
{% endblock content %}

articles/templates/articles/index.html
{% extends 'articles/base.html' %} {% block content %}
<h1 class="mb-3">All Articles</h1>
{% for article in articles %}
<div class="col-md-6">
  {% include 'articles/partials/_article.html' with article=article %}
</div>
{% endfor %} {% endblock content %}

articles/templates/articles/partials/_article.html
<div class="card border-primary mb-3 shadow">
  <div class="card-header">
    <h6 class="text-muted pt-2">
      Published by {{article.author.username}},
      <!---->
      about {{ article.created_at | timesince }} ago
    </h6>
  </div>
  <div class="card-body">
    <h4 class="card-title">
      <a
        href="{% url 'articles:detail' article.id %}"
        class="text-decoration-none"
      >{{ article.title }}</a>
    </h4>
    <p class="card-text text-muted">{{ article.excerpt }}</p>
  </div>
</div>

articles/templates/articles/partials/_header.html
<nav
  class="
    navbar navbar-expand-lg navbar-light
    bg-primary
    mb-3
    shadow-lg
    sticky-top
  "
>
  <div class="container">
    <a
      class="navbar-brand"
      href="{% url 'articles:list' %}"
    >
      <h3>BlogBro</h3>
    </a>
    <ul class="navbar-nav ms-auto">
      <li class="nav-item">
        <a class="nav-link" href="{% url 'articles:list' %}">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'articles:about' %}">About</a>
      </li>
      {% if user.is_authenticated %}
      <li class="nav-item">
        <a
          class="btn btn-dark nav-link text-white ms-2"
          href="{% url 'articles:create' %}"
        >New Article</a>
      </li>
      <li class="nav-item">
        <a class="nav-link ms-2" href="{% url 'logout' %}"
          >Logout, {{user.username}}</a
        >
      </li>
      {% else %}
      <li class="nav-item">
        <a
          class="btn btn-dark nav-link text-white ms-2"
          href="{% url 'login' %}"
          >Login/SignUp</a
        >
      </li>
      {% endif %}
    </ul>
  </div>
</nav>

users/templates/users/login.html
{% extends 'articles/base.html' %}

{% load crispy_forms_tags %}

{% block content %}
  <form method="POST" class="col-6 shadow-lg p-5 mx-auto mb-5">
    {% csrf_token %}
    <fieldset class="form-group">
      <legend class="border-bottom mb-4 text-center">
        <h2>Please login first</h2>
      </legend>
      {{form | crispy}}
    </fieldset>
    <div class="form-group mt-5 text-center">
      <button class="btn btn-outline-primary rounded-0 btn-lg mb-3" type="submit">
        Login
      </button>
    </div>
    <div class="border-top pt-3 text-center">
      <small class="text-muted"
        >Don't have an account?
        <a
          href="{% url 'register' %}"
          class="ms-1 text-primary fw-bold text-decoration-none"
          >Sign Up</a
        ></small
      >
    </div>
  </form>
{% endblock content %}

users/templates/users/register.html
{% extends 'articles/base.html' %}

{% load crispy_forms_tags %}

{% block content %}
  <form method="POST" class="col-6 mx-auto shadow-lg p-5 mb-5">
    {% csrf_token %}
    <fieldset class="form-group">
      <legend class="border-bottom mb-4 text-center">
        <h2>Join Now!</h2>
      </legend>
      {{form | crispy}}
    </fieldset>
    <div class="form-group mt-3 text-center text-break text-wrap">
      <button class="btn btn-outline-primary rounded-0 btn-lg mb-3" type="submit">
        Sign Up & Create Profile
      </button>
    </div>
    <div class="border-top pt-3 text-center">
      <small class="text-muted"
        >Already have an account?
        <a
          href="{% url 'login' %}"
          class="ms-1 text-primary fw-bold text-decoration-none"
          >Sign In</a
        ></small
      >
    </div>
  </form>
{% endblock content %}